###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
networks:
    default:
        name: epi

services:
    mariadb:
        container_name: epi_db
        image: 'mariadb:11.0'
        working_dir: /app
        volumes:
            - '.:/app'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=epidb
            - MYSQL_USER=epidba
            - MYSQL_PASSWORD=dba1000
        ports:
            - '8306:3306'

    webserver:
        container_name : epi_web
        image: 'nginx:alpine'
        working_dir: /app
        volumes:
            - '.:/app'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8080:80'

    php-fpm:
        container_name: epi_php
        build: phpdocker/php-fpm
        working_dir: /app
        volumes:
            - '.:/app'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini'
